// @ts-nocheck
import './app-shell';
import { authenticatedRequest } from './supabase-auth';
import { contractsPresentation } from './contracts-presentation';
const error = document.querySelector('#request-error'), tableBody = document.querySelector('#contract-table-body'), records = document.querySelector('#contract-records'), stageFilter = document.querySelector('#stage-filter'), responsibilityFilter = document.querySelector('#responsibility-filter'); let contractAccess = { contracts: [] };
function item(tag, text, className) { const el = document.createElement(tag); el.textContent = text; if (className) el.className = className; return el; }
function link(action) { const el = item('a', action.label, 'button'); el.href = action.href; return el; }
function render() { const presentation = contractsPresentation(contractAccess, { stage: stageFilter.value, responsibility: responsibilityFilter.value }); if (!presentation.contracts.length) { const row = item('tr', ''); const cell = item('td', presentation.emptyMessage, 'empty'); cell.colSpan = 7; row.append(cell); tableBody.replaceChildren(row); records.replaceChildren(item('p', presentation.emptyMessage, 'empty')); return; } tableBody.replaceChildren(...presentation.contracts.map(c => { const row = document.createElement('tr'), title = document.createElement('td'), statusCell = document.createElement('td'), actionCell = document.createElement('td'); title.append(item('strong', c.title), item('small', c.version)); statusCell.append(item('span', c.stage, `status ${c.statusTone}`)); actionCell.append(link(c.action)); row.append(title, item('td', c.counterparty), item('td', c.responsibility), statusCell, item('td', c.nextMilestone), item('td', c.lastActivity), actionCell); return row; })); records.replaceChildren(...presentation.contracts.map(c => { const el = document.createElement('article'); el.className = 'record contract-record'; el.append(item('strong', c.title), item('span', c.stage, `status ${c.statusTone}`), item('div', `Counterparty: ${c.counterparty}`), item('div', `Your responsibility: ${c.responsibility}`), link(c.action)); return el; })); }
async function load() { try { ({ home: contractAccess } = await authenticatedRequest('/api/home')); } catch (e) { error.hidden = false; error.textContent = e.message; } render(); }
stageFilter.addEventListener('change', render); responsibilityFilter.addEventListener('change', render); load();
